version: '3.3'
services:
  alist:
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data/alist:/opt/alist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: alist
    image: 'xhofe/alist:latest'
