version: '3.9'
services:
    memos:
        image: 'neosmemo/memos:stable'
        volumes:
            - '~/.memos/:/var/opt/memos'
        ports:
            - '5230:5230'
        container_name: memos
